name       : grantlee
version    : 5.2.0
release    : 5
source     :
    - https://github.com/steveire/grantlee/archive/v5.2.0.tar.gz : 139acee5746b957bdf1327ec0d97c604d4c0b9be42aec5d584297cb5ed6a990a
license    : LGPL-2.1-or-later
component  : programming.library
summary    : C++ string template engine based on the Django template system
description: |
    Grantlee is a set of Free Software libraries written using the Qt framework. Currently two libraries are shipped with Grantlee: Grantlee Templates and Grantlee TextDocument.

    The goal of Grantlee Templates is to make it easier for application developers to separate the structure of documents from the data they contain, opening the door for theming and advanced generation of other text such as code.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Script)
setup      : |
    %cmake_ninja -DLIB_SUFFIX=%LIBSUFFIX%
build      : |
    %ninja_build
install    : |
    %ninja_install
