name       : grantlee
version    : 5.3.1
release    : 6
source     :
    - https://github.com/steveire/grantlee/releases/download/v5.3.1/grantlee-5.3.1.tar.gz : ba288ae9ed37ec0c3622ceb40ae1f7e1e6b2ea89216ad8587f0863d64be24f06
license    : LGPL-2.1-or-later
component  : programming.library
summary    : C++ string template engine based on the Django template system
description: |
    Grantlee is a set of Free Software libraries written using the Qt framework. Currently two libraries are shipped with Grantlee: Grantlee Templates and Grantlee TextDocument.

    The goal of Grantlee Templates is to make it easier for application developers to separate the structure of documents from the data they contain, opening the door for theming and advanced generation of other text such as code.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Script)
setup      : |
    %cmake_ninja -DLIB_SUFFIX=%LIBSUFFIX%
build      : |
    %ninja_build
install    : |
    %ninja_install
