name       : grantlee
version    : 5.1.0
release    : 1
source     :
    - http://downloads.grantlee.org/grantlee-5.1.0.tar.gz : ea2e402466c74bb533eee2c7252209ec61cd93a5d236fecd625b4a0eb13a1478
license    : LGPL-2.1
component  : programming
summary    : C++ string template engine based on the Django template system
description: |
    Grantlee is a set of Free Software libraries written using the Qt framework. Currently two libraries are shipped with Grantlee: Grantlee Templates and Grantlee TextDocument.

    The goal of Grantlee Templates is to make it easier for application developers to separate the structure of documents from the data they contain, opening the door for theming and advanced generation of other text such as code.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Script)
setup      : |
    %cmake -DLIB_SUFFIX=%LIBSUFFIX% .
build      : |
    %make
install    : |
    %make_install
